# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Package, Deploy to exchange, Deploy to Cloud Hub - Prod

on:
  workflow_dispatch:
    inputs:
      runtimeVersion:
        description: 'Version of the runtime that will run the deployed asset'
        required: true
        default: '4.4.0'
        type: choice
        options:
        - 4.4.0
jobs:
  
  package_deployExchange_deployCHProd:
    name: Package, and deploy to exchange, then deploy to Cloud Hub - Prod
    runs-on: ubuntu-latest
    environment: 
      name: Prod
    steps:
    
    - name: Check out this repo
      id: checkout-repo
      uses: actions/checkout@v3
    
    - name: Set up cache for Maven Dependencies(./m2/repository)
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Checkout latest release tag
      run: |
        LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        git checkout $LATEST_TAG

    - name: Package and deploy to Exchange
      id: package-deploy-exchange
      env:
        MuleSoft_EE_Rep_Username: ${{ secrets.MuleSoft_EE_Rep_Username }}
        MuleSoft_EE_Rep_Password: ${{ secrets.MuleSoft_EE_Rep_Password }}
        AP_CICD_ConnectedApp_ClientID: ${{ secrets.AP_CICD_ConnectedApp_ClientID }}
        AP_CICD_ConnectedApp_ClientSecret: ${{ secrets.AP_CICD_ConnectedApp_ClientSecret }}
        AP_Organization_ID: ${{ secrets.AP_Organization_ID }}
      run: mvn deploy -DskipMunitTests -s .maven/settings.xml

    - name: Deploy to Cloudhub on Prod
      id: deploy-ch-dev
      env:
        MuleSoft_EE_Rep_Username: ${{ secrets.MuleSoft_EE_Rep_Username }}
        MuleSoft_EE_Rep_Password: ${{ secrets.MuleSoft_EE_Rep_Password }}
        AP_CICD_ConnectedApp_ClientID: ${{ secrets.AP_CICD_ConnectedApp_ClientID }}
        AP_CICD_ConnectedApp_ClientSecret: ${{ secrets.AP_CICD_ConnectedApp_ClientSecret }}
        AP_Organization_ID: ${{ secrets.AP_Organization_ID }}
        AP_Environment: Prod
        AP_ENV_ClientID: ${{ secrets.AP_Prod_ClientID }}
        AP_ENV_ClientSecret: ${{ secrets.AP_Prod_ClientSecret }}
        AP_Full_Application_Name: ${{  vars.AP_Application_Name }}
        AP_CH_Runtime_Version: ${{ inputs.runtimeVersion == '' && '4.4.0' || inputs.runtimeVersion }}
        AP_Target: ${{ vars.AP_PrivateSpace_Prod_Name}}
        AP_replicas: ${{ vars.AP_replicas }}
        AP_vcores: ${{ vars.AP_vcores }}
      run: 
        mvn deploy -DmuleDeploy -DskipMunitTests -s .maven/settings.xml
            -Denv.AP_Environment=$AP_Environment 
            -Dapp.name=$AP_Full_Application_Name 
            -DAP_Organization_ID=$AP_Organization_ID 
            -DAP_CICD_ConnectedApp_ClientID=$AP_CICD_ConnectedApp_ClientID 
            -DAP_CICD_ConnectedApp_ClientSecret=$AP_CICD_ConnectedApp_ClientSecret 
            -DAP_ENV_ClientID=$AP_ENV_ClientID 
            -DAP_ENV_ClientSecret=$AP_ENV_ClientSecret 
            -DAP_CH_Runtime_Version=$AP_CH_Runtime_Version 
            -DAP_Target=$AP_Target
            -DAP_replicas=$AP_replicas
            -DAP_vcores=$AP_vcores
            -Dmule.env=$AP_Environment