# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Unit tests, package, deploy to Cloudhub 

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment to deploy'
        required: true
        type: environment
      runtimeVersion:
        description: 'Version of the runtime that will run the deployed asset'
        required: true
        default: '4.4.0'
        type: choice
        options:
        - 4.4.0
      deployExchange:
        description: "Select to deploy to exchange before cloudhub"
        required: true
        default: false
        type: boolean

jobs:
  unitTest-package-deployCloudHub:
    name: Unit tests, package and deploy to Cloudhub on target environment
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:

    - name: Check out this repo
      id: checkout-repo
      uses: actions/checkout@v3
    
    - name: Set up cache for Maven Dependencies(./m2/repository)
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Setup JDK 8
      id: setup-jdk
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
  
    - name: Package and deploy to Exchange
      id: package-deploy-exchange
      if: inputs.deployExchange
      env:
        MuleSoft_EE_Rep_Username: ${{ secrets.MuleSoft_EE_Rep_Username }}
        MuleSoft_EE_Rep_Password: ${{ secrets.MuleSoft_EE_Rep_Password }}
        AP_CICD_ConnectedApp_ClientID: ${{ secrets.AP_CICD_ConnectedApp_ClientID }}
        AP_CICD_ConnectedApp_ClientSecret: ${{ secrets.AP_CICD_ConnectedApp_ClientSecret }}
        AP_Organization_ID: ${{ secrets.AP_Organization_ID }}
      run: mvn deploy -DskipMunitTests -s .maven/settings.xml

    - name: Run unit tests, package and deploy to Cloudhub on ${{ inputs.environment }}
      id: unitTest-package-deployCH
      env:
        AP_CICD_ConnectedApp_ClientID: ${{ secrets.AP_CICD_ConnectedApp_ClientID }}
        AP_CICD_ConnectedApp_ClientSecret: ${{ secrets.AP_CICD_ConnectedApp_ClientSecret }}
        AP_Organization_ID: ${{ secrets.AP_Organization_ID }}
        AP_Environment: ${{ inputs.environment }}
        AP_ENV_ClientID: ${{ inputs.environment == 'Dev' && secrets.AP_DEV_ClientID || inputs.environment == 'UAT' && secrets.AP_UAT_ClientID || inputs.environment == 'Prod' && secrets.AP_Prod_ClientID}}
        AP_ENV_ClientSecret: ${{ inputs.environment == 'Dev' && secrets.AP_DEV_ClientSecret || inputs.environment == 'UAT' && secrets.AP_UAT_ClientSecret || inputs.environment == 'Prod' && secrets.AP_Prod_ClientSecret}}
        AP_Full_Application_Name: ${{  format('{0}{1}', vars.AP_Application_Name, inputs.environment == 'Dev' && vars.AP_DEV_APPLICATION_NAME_SUFFIX || inputs.environment == 'UAT' && vars.AP_UAT_APPLICATION_NAME_SUFFIX || inputs.environment == 'Prod' && vars.AP_PROD_APPLICATION_NAME_SUFFIX) }}
        AP_CH_Runtime_Version: ${{ inputs.runtimeVersion == '' && '4.4.0' || inputs.runtimeVersion }}
        AP_Target: ${{ inputs.environment == 'Prod' && vars.AP_PrivateSpace_Prod_Name || vars.AP_PrivateSpace_Sandbox_Name }}
        AP_replicas: ${{ vars.AP_replicas }}
        AP_vcores: ${{ vars.AP_vcores }}
        MuleSoft_EE_Rep_Username: ${{ secrets.MuleSoft_EE_Rep_Username }}
        MuleSoft_EE_Rep_Password: ${{ secrets.MuleSoft_EE_Rep_Password }}
      run: mvn deploy -B -s .maven/settings.xml -DmuleDeploy
            -Denv.AP_Environment=$AP_Environment 
            -Dapp.name=$AP_Full_Application_Name 
            -DAP_Organization_ID=$AP_Organization_ID 
            -DAP_CICD_ConnectedApp_ClientID=$AP_CICD_ConnectedApp_ClientID 
            -DAP_CICD_ConnectedApp_ClientSecret=$AP_CICD_ConnectedApp_ClientSecret 
            -DAP_ENV_ClientID=$AP_ENV_ClientID 
            -DAP_ENV_ClientSecret=$AP_ENV_ClientSecret 
            -DAP_CH_Runtime_Version=$AP_CH_Runtime_Version 
            -DAP_Target=$AP_Target
            -DAP_replicas=$AP_replicas
            -DAP_vcores=$AP_vcores
            -Dmule.env=$AP_Environment