# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run Unit tests, package, and deploy to cloudhub

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment to deploy'
        required: true
        type: environment
      runtimeVersion:
        description: 'Version of the runtime that will run the deployed asset'
        required: true
        default: '4.4.0'
        type: choice
        options:
        - 4.4.0
      target:
        description: 'Private or shared space that is the target of the deployment'
        required: true
        default: 'Cloudhub-US-East-2'
        type: choice
        options:
        - Cloudhub-US-East-2

jobs:
  unittest:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:

    - name: LOG DEBUG environment
      run: echo Environment is ${{ inputs.environment }}

    - name: LOG DEBUG full application name - Repo Variable and Env Variable
      env:
        AP_Application_Name: ${{ vars.AP_Application_Name }}
        AP_APPLICATION_NAME_SUFFIX: ${{  vars.AP_APPLICATION_NAME_SUFFIX }}
        AP_Full_Application_Name: ${{  format('{0}{1}', vars.AP_Application_Name, vars.AP_APPLICATION_NAME_SUFFIX) }}
      run: |
        echo $AP_Application_Name
        echo $AP_APPLICATION_NAME_SUFFIX
        echo $AP_Full_Application_Name

    - name: LOG DEBUG PRIVATESPACE_SANDBOX_NAME - Org Variable
      env:
        PRIVATESPACE_SANDBOX_NAME: ${{ vars.PRIVATESPACE_SANDBOX_NAME }}
      run: echo $PRIVATESPACE_SANDBOX_NAME

    - name: Check out this repo
      id: checkout-repo
      uses: actions/checkout@v3
    
    - name: Set up cache for Maven Dependencies(./m2/repository)
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Setup JDK 8
      id: setup-jdk
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven     
    
    - name: Run MUnits
      id: build
      run: mvn clean test -B -s .maven/settings.xml
      env:
        MuleSoft_EE_Rep_Username: ${{ secrets.MuleSoft_EE_Rep_Username }}
        MuleSoft_EE_Rep_Password: ${{ secrets.MuleSoft_EE_Rep_Password }}
        AP_CICD_ConnectedApp_ClientID: ${{ secrets.AP_CICD_ConnectedApp_ClientID }}
        AP_CICD_ConnectedApp_ClientSecret: ${{ secrets.AP_CICD_ConnectedApp_ClientSecret }}

  build:
    needs: unittest
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    
    - name: Check out this repo
      id: checkout-repo
      uses: actions/checkout@v3
    
    - name: Set up cache for Maven Dependencies(./m2/repository)
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Build the artifact
      id: build
      env:
        MuleSoft_EE_Rep_Username: ${{ secrets.MuleSoft_EE_Rep_Username }}
        MuleSoft_EE_Rep_Password: ${{ secrets.MuleSoft_EE_Rep_Password }}
        AP_Organization_ID: ${{ secrets.AP_Organization_ID }}
        AP_Environment: ${{ inputs.environment }}
        AP_CICD_ConnectedApp_ClientID: ${{ secrets.AP_CICD_ConnectedApp_ClientID }}
        AP_CICD_ConnectedApp_ClientSecret: ${{ secrets.AP_CICD_ConnectedApp_ClientSecret }}
        AP_ENV_ClientID: ${{ inputs.environment == 'Dev' && secrets.AP_DEV_ClientID || inputs.environment == 'UAT' && secrets.AP_UAT_ClientID || inputs.environment == 'Prod' && secrets.AP_Prod_ClientID}}
        AP_ENV_ClientSecret: ${{ inputs.environment == 'Dev' && secrets.AP_DEV_ClientSecret || inputs.environment == 'UAT' && secrets.AP_UAT_ClientSecret || inputs.environment == 'Prod' && secrets.AP_Prod_ClientSecret}}
        AP_CH_Runtime_Version: ${{ inputs.runtimeVersion }}
        environment: ${{ inputs.environment }}
      run: mvn -B package -DskipMunitTests -s .maven/settings.xml
      
    - name: Stamp artifact file name with commit hash
      id: stamp-commit-hash
      run: |
        artifactName1=$(ls target/*.jar | head -1)
        commitHash=$(git rev-parse --short "$GITHUB_SHA")
        artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
        mv $artifactName1 $artifactName2

    - name: Upload artifact
      id: upload-artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: target/*.jar

  deploycloudhub:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    
    - name: Check out this repo
      id: checkout-repo
      uses: actions/checkout@v3
    
    - name: Set up cache for Maven Dependencies(./m2/repository)
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    
    - name: Download artifact
      id: download-artifact
      uses: actions/download-artifact@v3
      with:
        name: artifacts
        path: target/*.jar

    - name: Deploy to Cloudhub on ${{ inputs.environment }}
      id: deployCH
      env:
        AP_CICD_ConnectedApp_ClientID: ${{ secrets.AP_CICD_ConnectedApp_ClientID }}
        AP_CICD_ConnectedApp_ClientSecret: ${{ secrets.AP_CICD_ConnectedApp_ClientSecret }}
        AP_Organization_ID: ${{ secrets.AP_Organization_ID }}
        AP_Environment: ${{ inputs.environment }}
        AP_Full_Application_Name: ${{  format('{0}{1}', vars.AP_Application_Name, vars.AP_APPLICATION_NAME_SUFFIX) }}
      run: mvn -B deploy -DmuleDeploy -DskipMunitTests -Denv.AP_Environment=$AP_Environment -Dapp.name=$AP_Full_Application_Name